version: '3'
networks: 
    web:
services: 
    web:
        image: node:12.18.3
        volumes: 
            - ./web:/web
        ports: 
            - 3001:3000
        command: bash -c "cd /web"
        networks: 
            - web