version: '3'
networks: 
    web:
services: 
    web:
        image: jorgelba/reactjs:1.0.0
        volumes: 
            - ./web:/web
        ports: 
            - 3000:3000
        networks: 
            - web
        stdin_open: true